draw:
	@make -C basic draw
	@make -C coord draw
	@make -C expletives draw
	@make -C gsd draw
	@make -C sequoia draw
	@make -C web draw

clean:
	@make -C basic clean
	@make -C coord clean
	@make -C expletives clean
	@make -C gsd clean
	@make -C sequoia clean
	@make -C web clean
